name: Build and deploy Node.js app to Azure Web App - HW9B-NicholasNguyen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install and test
        run: |
          npm install
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git/*" -x "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
<<<<<<< HEAD
=======
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
>>>>>>> ae496e3457022587d14dbe6a21120818867b3217

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
<<<<<<< HEAD

      - name: List files after unzipping (optional for debugging)
        run: ls -al

      - name: Deploy to Azure Web App
=======
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DBC16D05E6D741A6A8B241DC799C9712 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF6CC346625C4A0C83952DEC74D5A9C2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4BF2DD5E89934CD98AAED185E7D3C50C }}

      - name: 'Deploy to Azure Web App'
>>>>>>> ae496e3457022587d14dbe6a21120818867b3217
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "HW9B-NicholasNguyen"
          slot-name: "Production"
          package: .
<<<<<<< HEAD
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24A7FB2FFF184AFBA0470A5E440A5E81 }}
=======
          
>>>>>>> ae496e3457022587d14dbe6a21120818867b3217
